# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='profile_picture',
        ),
    ]
