# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:44
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160719_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='users/%d/%m/%y'),
        ),
    ]
