# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:32
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160720_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='users/%d/%m/%y'),
        ),
    ]
