# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160722_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverpic', models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/%d')),
            ],
        ),
    ]
